"""``validate-aftershock``: the aftershock forecast service, offline, on committed fixtures.

What the gate proves, in about a minute:

1. **The fixtures are the ones the numbers came from.** Each committed ComCat slice matches the
   sha256 in its ``provenance.json``; the declared mainshock of each sequence agrees with the
   catalogue's own solution (time, magnitude, epicentre); and every committed ETAS fit's
   ``training_catalog_hash`` recomputes from the slice, so a fit cannot silently belong to
   different data.
2. **Both sequences are forecast and scored**, at all three issue times (+1 h, +1 d, +7 d) over a
   7-day horizon, against the window that actually closed: the CSEP N-test on the gridded
   forecast and a Poisson count check on each rung of the magnitude ladder. Reports are written
   to ``reports/validate-aftershock/``.
3. **Probabilities are well formed**: every one in [0, 1], and non-increasing with magnitude,
   with the expected count non-increasing too.
4. **Leakage is refused, not filtered.** A history carrying one event at the issue time raises
   :class:`~rupture.adapters.forecasting.leakage.LeakageError`; so does a fit whose training
   catalogue reaches its cutoff.

The gate does *not* re-run the EM fits: the six of them take about four minutes, which is not a
gate. It uses the committed fits (regenerated by ``tests.fixtures.aftershock.make_fits``) and
checks that they belong to the committed catalogue. To stay inside its budget it also runs at a
coarser 0.2-degree cell and 5 stochastic continuations, where the published validation in
``docs/AFTERSHOCK.md`` uses the region's own 0.1 degree and 100; the gate's expected counts are
therefore noisier than the published ones and are not the numbers to quote.

It does not assert that the forecasts were *good*. They were not, in places, and
``docs/AFTERSHOCK.md`` says where. A gate that failed whenever a forecast scored badly would be a
gate against reporting the truth.
"""

from __future__ import annotations

import json
import shutil
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

from rupture.adapters.evaluation.pycsep import PyCSEPEvaluator
from rupture.adapters.forecasting.etas_mizrahi import MizrahiETAS
from rupture.adapters.forecasting.grid import build_lattice
from rupture.adapters.forecasting.leakage import LeakageError, assert_all_before
from rupture.domain import AftershockForecast, Catalog, FitResult, Region, TestName
from rupture.services.aftershock.evaluation import (
    ALPHA,
    WindowOutcome,
    evaluate_window,
    render_markdown,
    write_report,
)
from rupture.services.aftershock.evaluation import SequenceOutcome as Outcome
from rupture.services.aftershock.forecaster import (
    AftershockForecaster,
    scheduled_fit_cutoff,
)
from rupture.services.aftershock.sequences import (
    ISSUE_OFFSETS,
    SEQUENCES,
    FixtureError,
    SequenceSpec,
    check_against_catalog,
    fixture_coverage_end,
    load_committed_fits,
    load_parent_region,
    load_sequence_catalog,
)
from rupture.services.aftershock.window import aftershock_zone_radius_km
from rupture.validation.result import GateResult, GateStatus

GATE_HORIZON = timedelta(days=7)
GATE_SIMULATIONS = 5  # enough to exercise the path; the published numbers use 100
GATE_CELL_SIZE_DEG = 0.2  # coarser than the region's 0.1 so the gate fits its budget
CSEP_SIMULATIONS = 200
RUNTIME_BUDGET_S = 90.0


def run(repo_root: Path) -> GateResult:  # noqa: PLR0915 - a gate is a checklist
    started = time.perf_counter()
    out_dir = repo_root / "reports" / "validate-aftershock"
    shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    findings: list[str] = []
    failures: list[str] = []
    forecaster = AftershockForecaster(
        n_simulations=GATE_SIMULATIONS, cell_size_deg=GATE_CELL_SIZE_DEG
    )
    evaluator = PyCSEPEvaluator()

    for name, spec in sorted(SEQUENCES.items()):
        try:
            catalog = load_sequence_catalog(spec, repo_root)
        except FixtureError as exc:
            failures.append(f"{name}: {exc}")
            continue
        parent = load_parent_region(spec, repo_root)
        coverage_end = fixture_coverage_end(spec, repo_root)
        region = forecaster.zone(spec.mainshock, parent)
        findings.append(
            f"{name}: {len(catalog)} events, zone radius "
            f"{aftershock_zone_radius_km(spec.mainshock.magnitude):.0f} km, region {region.id}, "
            f"Mc {region.mc.mc if region.mc else None}, coverage ends {coverage_end.date()}"
        )
        failures.extend(check_against_catalog(spec, catalog))

        fits = load_committed_fits(spec, repo_root)
        if not fits:
            failures.append(
                f"{name}: no committed fits under tests/fixtures/aftershock/fits/{name}; "
                "regenerate with `uv run python -m tests.fixtures.aftershock.make_fits`"
            )
            continue
        failures.extend(_check_fits(spec, catalog, region, fits, forecaster, findings))

        windows: list[WindowOutcome] = []
        for issue_label, offset in ISSUE_OFFSETS:
            issue_time = spec.mainshock.origin_time + offset
            cutoff = scheduled_fit_cutoff(spec.mainshock.origin_time, issue_time)
            fit = fits.get(cutoff.isoformat())
            if fit is None:
                failures.append(f"{name}: no committed fit for cutoff {cutoff.isoformat()}")
                continue
            if issue_time + GATE_HORIZON > coverage_end:  # pragma: no cover - fixture covers it
                failures.append(
                    f"{name}: the +{issue_label} 7d window ends after catalogue coverage"
                )
                continue
            issuance = forecaster.issue(
                history=catalog.before(issue_time),
                region=region,
                mainshock=spec.mainshock,
                fit=fit,
                issue_time=issue_time,
                horizon=GATE_HORIZON,
            )
            failures.extend(_check_probabilities(name, issue_label, issuance.forecast))
            windows.append(
                evaluate_window(
                    issuance=issuance,
                    catalog=catalog,
                    sequence_id=name,
                    issue_label=issue_label,
                    evaluator=evaluator,
                    alpha=ALPHA,
                    csep_simulations=CSEP_SIMULATIONS,
                )
            )

        outcome = Outcome(
            sequence_id=name,
            description=spec.description,
            mainshock_event_id=spec.mainshock.event_id,
            mainshock_time=spec.mainshock.origin_time.isoformat(),
            mainshock_magnitude=spec.mainshock.magnitude,
            region_id=region.id,
            zone_radius_km=round(aftershock_zone_radius_km(spec.mainshock.magnitude), 1),
            n_cells=build_lattice(region).n_cells,
            mc=region.mc.mc if region.mc is not None else float("nan"),
            target_min_magnitude=region.target_min_magnitude,
            catalog_coverage_end=coverage_end.isoformat(),
            n_catalog_events=len(catalog),
            windows=windows,
            skipped=[
                f"gate scores the {int(GATE_HORIZON.total_seconds() // 86400)}d horizon only; "
                "`rupture aftershock validate` scores 1d/7d/30d"
            ],
            evaluated_at=datetime.now(tz=UTC).isoformat(),
        )
        json_path, md_path = write_report(outcome, out_dir)
        findings.append(
            f"{name}: {len(windows)} window(s) scored -> {json_path.name}, {md_path.name}"
        )
        for window in windows:
            n_test = next((r for r in window.csep if r.test == TestName.N.value), None)
            observed = window.n_observed_above_target
            findings.append(
                f"{name} +{window.issue_label} {window.horizon}: expected "
                f"{window.total_expected_above_target:.2f}, observed {observed}"
                + (f", N-test passed={n_test.passed}" if n_test else "")
            )
        if not md_path.exists() or not json_path.exists():  # pragma: no cover - write_report wrote
            failures.append(f"{name}: report not written")
        if not render_markdown(outcome).strip():  # pragma: no cover - defensive
            failures.append(f"{name}: empty report")

    failures.extend(_check_leakage_refused(repo_root, forecaster, findings))

    elapsed = time.perf_counter() - started
    findings.append(f"runtime {elapsed:.1f}s (budget {RUNTIME_BUDGET_S:.0f}s)")
    if elapsed > RUNTIME_BUDGET_S:
        findings.append("warning: the gate exceeded its runtime budget")
    (out_dir / "summary.json").write_text(
        json.dumps(
            {"findings": findings, "failures": failures, "runtime_s": round(elapsed, 1)},
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    status = GateStatus.PASSED if not failures else GateStatus.FAILED
    return GateResult(name="validate-aftershock", status=status, findings=[*failures, *findings])


def _check_fits(  # noqa: PLR0917 - a checklist, called once
    spec: SequenceSpec,
    catalog: Catalog,
    region: Region,
    fits: dict[str, FitResult],
    forecaster: AftershockForecaster,
    findings: list[str],
) -> list[str]:
    """Every committed fit converged, is sub-critical, and was trained on this exact slice."""
    failures: list[str] = []
    for cutoff_iso, fit in sorted(fits.items()):
        cutoff = datetime.fromisoformat(cutoff_iso)
        training = MizrahiETAS.training_slice(catalog, region, cutoff, fit.mc)
        if training.event_hash() != fit.training_catalog_hash:
            failures.append(
                f"{spec.id} fit {cutoff_iso}: training_catalog_hash does not recompute from the "
                "committed slice (the fit and the catalogue have drifted apart)"
            )
        if fit.converged is not True:
            failures.append(f"{spec.id} fit {cutoff_iso}: did not converge")
        if fit.diagnostics.get("at_bound"):
            findings.append(
                f"{spec.id} fit {cutoff_iso}: parameters on an inversion bound: "
                f"{fit.diagnostics['at_bound']}"
            )
        branching = fit.diagnostics.get("branching_ratio")
        if branching is None or not 0.0 < float(branching) < 1.0:
            failures.append(
                f"{spec.id} fit {cutoff_iso}: branching ratio {branching} is not sub-critical; "
                "its stochastic continuations are not usable"
            )
        else:
            findings.append(
                f"{spec.id} fit {cutoff_iso}: n={fit.n_events} branching={float(branching):.3f} "
                f"b={fit.diagnostics['b_value']:.3f} "
                f"(fixed={fit.diagnostics.get('beta_fixed')})"
            )
        if fit.model_id != forecaster.model_for(region).model_id:  # pragma: no cover - defensive
            failures.append(f"{spec.id} fit {cutoff_iso}: unexpected model {fit.model_id}")
    return failures


def _check_probabilities(
    sequence_id: str, issue_label: str, forecast: AftershockForecast
) -> list[str]:
    """[0, 1], ordered by magnitude, and non-increasing in both probability and expected count."""
    failures: list[str] = []
    previous_p = 1.0
    previous_lambda = float("inf")
    for rung in forecast.probabilities:
        where = f"{sequence_id} +{issue_label} M>={rung.magnitude}"
        if not 0.0 <= rung.probability <= 1.0:  # pragma: no cover - domain validator forbids it
            failures.append(f"{where}: probability {rung.probability} outside [0, 1]")
        if rung.probability > previous_p + 1e-12:
            failures.append(
                f"{where}: probability {rung.probability} exceeds the one at the rung below "
                f"({previous_p})"
            )
        if rung.expected_count > previous_lambda + 1e-12:
            failures.append(
                f"{where}: expected count {rung.expected_count} exceeds the rung below "
                f"({previous_lambda})"
            )
        previous_p, previous_lambda = rung.probability, rung.expected_count
    return failures


def _check_leakage_refused(
    repo_root: Path, forecaster: AftershockForecaster, findings: list[str]
) -> list[str]:
    """Inject one event at the issue time and require a refusal, not a silent filter."""
    spec = SEQUENCES["gorkha"]
    catalog = load_sequence_catalog(spec, repo_root)
    parent = load_parent_region(spec, repo_root)
    region = forecaster.zone(spec.mainshock, parent)
    fits = load_committed_fits(spec, repo_root)
    issue_time = spec.mainshock.origin_time + timedelta(days=1)
    cutoff = scheduled_fit_cutoff(spec.mainshock.origin_time, issue_time)
    fit = fits.get(cutoff.isoformat())
    if fit is None:  # pragma: no cover - checked above
        return ["leakage check: no committed gorkha fit at +1 d"]

    history = catalog.before(issue_time)
    future = next((e for e in catalog.events if e.origin_time >= issue_time), None)
    if future is None:  # pragma: no cover - the slice runs to +46 d
        return ["leakage check: the fixture has no event after the issue time to inject"]
    poisoned = history.model_copy(update={"events": (*history.events, future)})

    failures: list[str] = []
    try:
        forecaster.issue(
            history=poisoned,
            region=region,
            mainshock=spec.mainshock,
            fit=fit,
            issue_time=issue_time,
            horizon=GATE_HORIZON,
        )
    except LeakageError as exc:
        findings.append(f"leakage refused on issue: {exc}".split(" (latest")[0])
    else:
        failures.append(
            "leakage NOT refused: a history containing an event at/after the issue time was "
            "accepted by AftershockForecaster.issue"
        )

    try:
        assert_all_before(poisoned, cutoff, what="gate leakage probe")
    except LeakageError as exc:
        findings.append(f"leakage refused by assert_all_before: {str(exc).split(' (latest')[0]}")
    else:  # pragma: no cover - defensive
        failures.append("assert_all_before accepted a catalogue reaching the cutoff")

    # The fit path truncates first and then asserts, so it does not raise on a poisoned
    # catalogue; what has to hold is that nothing at or after the cutoff survives the truncation.
    training = MizrahiETAS.training_slice(poisoned, region, cutoff, fit.mc)
    latest = training.max_origin_time()
    if latest is not None and latest >= cutoff:  # pragma: no cover - the filter is the domain's
        failures.append(
            f"MizrahiETAS.training_slice kept an event at {latest.isoformat()}, at/after the "
            f"cutoff {cutoff.isoformat()}"
        )
    else:
        findings.append(
            f"fit training slice truncated at {cutoff.isoformat()} "
            f"(latest kept {latest.isoformat() if latest else 'none'})"
        )
    return failures
